config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/bereinigen'
  get 'home/leeren'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def bereinigen
		@bereinigen = List.where(:erledigt => true).destroy_all
		redirect_to lists_url, notice: 'Erledigte Aufgaben endgültig gelöscht.'
	end

	def leeren
		@leeren = List.all.destroy_all
		redirect_to lists_url, notice: 'Alle Aufgaben endgültig gelöscht.'
	end	


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'Neue Aufgabe angelegt.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'Erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Aufgabe endgültig gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:Beschreibung, :verantwortlich, :erledigt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
    <%= render 'lists/navbar' %>
  	<div class="container">
      <%= render 'flash' %>
      <%= yield %>
    </div>      
  </body>
</html>

app/views/lists/_flash.html.erb
</br>
<% flash.each do |name, msg| %>
  		<div class="alert alert-warning alert-dismissible">
  			<button type="button" class="close" aria-label="Close" data-dismiss="alert">
  				<span aria-hidden="true" class="btn-sm">&times;</span>
			</button>
  			<%= content_tag(:div, msg) %>
		</div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Beschreibung %>
    <%= form.text_field :Beschreibung, id: :list_Beschreibung %>
  </div>

  <div class="field">
    <%= form.label :verantwortlich %>
    <%= form.text_field :verantwortlich, id: :list_verantwortlich %>
  </div>

  <div class="field">
    <% form.label :erledigt %>
    <%= form.check_box :erledigt, id: :list_erledigt %> erledigt
  </div>

  <div class="actions">
    <%= form.submit "Speichern" %>
  </div>
<% end %>

app/views/lists/_form_bereinigen_html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= link_to 'Erledigte Aufgaben löschen', home_bereinigen_path, class:"btn btn-light", data: { confirm: 'Bist Du sicher?' } %>

<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Beschreibung %>
    <%= form.text_field :Beschreibung, id: :list_Beschreibung %>
  </div>

  <div class="form-group">
    <%= form.label :verantwortlich %>
    <input class="form-control" id="list_verantwortlich">
    <% form.text_field :verantwortlich, id: :list_verantwortlich %>
  </div>

  <div class="actions">
    <%= form.submit "Aufgabe hinzufügen" %>
  </div>
<% end %>

app/views/lists/_form_index2.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <tr class="table-success">
  	<td>
      <div class="form-group">
        <% form.label :Beschreibung %>
        <%= form.text_field :Beschreibung, id: :list_Beschreibung, class:"form-control" %>
      </div>
   	</td>
  	<td>
      <div class="form-group">
        <% form.label :verantwortlich %>
        <%= form.text_field :verantwortlich, id: :list_verantwortlich, class:"form-control" %>
      </div>
    </td>
    <td></td>
  	<td>
      <div class="actions">
        <%= form.submit "hinzufügen", class: "btn btn-secondary btn-sm" %>
    </td>
  </tr>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Aufgabenliste", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="verantwortlich" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Filtern</button>
    </form>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Aufgabe bearbeiten   </h1>

<%= render 'form', list: @list %>

<%= link_to 'anzeigen', @list %> |
<%= link_to 'zurück', lists_path %>

app/views/lists/index.html.erb
<h1>Aufgaben</h1>
<table class="table table-hover">
  <thead>
    <tr class="table-primary">
      <th>Beschreibung</th>
      <th>verantwortlich</th>
      <th><center>Status ändern</center></th>
      <th>Aktion</th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <% if list.erledigt %>
        <tr class="table-secondary">
         <td class="striker"><%= link_to list.Beschreibung, edit_list_path(list) %><% list.Beschreibung %></td> 
          <td><%= list.verantwortlich %></td>
         
          <td>
            <center>
            <%= form_for(list) do |f| %>
                <%= f.text_field :Beschreibung, type: 'hidden' %>
                <%= f.check_box :erledigt, id: :list_erledigt, :checked => false, :style => 'visibility: hidden' %> 
                <%= f.submit "reaktivieren", class: "btn btn-secondary btn-sm" %>
            <% end %>
            </center>
          </td>
         
          <td>
            <% link_to 'anzeigen', list %>
            <% link_to 'bearbeiten', edit_list_path(list) %>

            <%= link_to 'löschen', list, class: "btn btn-secondary btn-sm", method: :delete, data: { confirm: 'Bist Du sicher?' } %>    
          </td>
        </tr>
      <% elsif %>
        <tr>
          <td><%= link_to list.Beschreibung, edit_list_path(list) %><% list.Beschreibung %></td>
          <td><%= list.verantwortlich %></td>
         
          <td>
            <center>
            <%= form_for(list) do |f| %>
                <%= f.text_field :Beschreibung, type: 'hidden' %>
                <%= f.check_box :erledigt, id: :list_erledigt, :checked => true, :style => 'visibility: hidden' %> 
                <%= f.submit "erledigt", class: "btn btn-secondary btn-sm" %>
            <% end %>
            </center>
          </td>
         
          <td>
            <% link_to 'anzeigen', list %>
            <% link_to 'bearbeiten', edit_list_path(list) %>
            <%= link_to 'löschen', list, class: "btn btn-secondary btn-sm", method: :delete, data: { confirm: 'Bist Du sicher?' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
      
        <%= render 'form_index2', list: @list %>
     

  </tbody>
</table>

<br>

<% link_to 'Neue Aufgabe', new_list_path, class:"btn btn-light" %>
<%= link_to 'Erledigte Aufgaben löschen', home_bereinigen_path, class:"btn btn-secondary text-light", data: { confirm: 'Bist Du sicher?' } %>
<BR/><BR/>

<%= link_to 'Liste leeren', home_leeren_path, class:"btn btn-danger text-light", data: { confirm: 'Bist Du sicher? Alle Aufgaben weren endgültig gelöscht!' } %>

app/views/lists/new.html.erb
<h1>Neue Aufgabe</h1>

<%= render 'form', list: @list %>

<%= link_to 'zurück', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Beschreibung:</strong>
  <%= @list.Beschreibung %>
</p>

<p>
  <strong>verantwortlich:</strong>
  <%= @list.verantwortlich %>
</p>

<p>
  <strong>erledigt:</strong>
  <%= @list.erledigt %>
</p>

<%= link_to 'bearbeiten', edit_list_path(@list) %> |
<%= link_to 'zurück', lists_path %>